// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbJOb6GQhE5YC54bX5xpaKQdueen6TXug',
    appId: '1:960801961242:web:cc373b6d3e9c0f4961a8a3',
    messagingSenderId: '960801961242',
    projectId: 'teachers-attendance-app',
    authDomain: 'teachers-attendance-app.firebaseapp.com',
    storageBucket: 'teachers-attendance-app.firebasestorage.app',
    measurementId: 'G-2H5HFTBJYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmevp9n8d8MONyW3-x9PqbuI-oJJpes2U',
    appId: '1:960801961242:android:804cd258b4b08ae661a8a3',
    messagingSenderId: '960801961242',
    projectId: 'teachers-attendance-app',
    storageBucket: 'teachers-attendance-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUou8ayuNmWsydeIiifMBQXqDSQto54ec',
    appId: '1:960801961242:ios:7d3e428263aa2cea61a8a3',
    messagingSenderId: '960801961242',
    projectId: 'teachers-attendance-app',
    storageBucket: 'teachers-attendance-app.firebasestorage.app',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUou8ayuNmWsydeIiifMBQXqDSQto54ec',
    appId: '1:960801961242:ios:7d3e428263aa2cea61a8a3',
    messagingSenderId: '960801961242',
    projectId: 'teachers-attendance-app',
    storageBucket: 'teachers-attendance-app.firebasestorage.app',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbJOb6GQhE5YC54bX5xpaKQdueen6TXug',
    appId: '1:960801961242:web:a7840bca39d437b661a8a3',
    messagingSenderId: '960801961242',
    projectId: 'teachers-attendance-app',
    authDomain: 'teachers-attendance-app.firebaseapp.com',
    storageBucket: 'teachers-attendance-app.firebasestorage.app',
    measurementId: 'G-FGLYXR4C4E',
  );
}
